services:
  blog-next:
    container_name: blog-next
    image: suqingyao/blog-next:latest
    volumes:
      - ./public:/app/public
    restart: always
    ports:
      - '2323:2323'
    environment:
      - NODE_ENV=production
