services:
  blog-next:
    container_name: blog-next
    image: crpi-xc0zmevg27znkp2g.cn-chengdu.personal.cr.aliyuncs.com/suqingyao/blog-next:latest
    volumes:
      - ./public:/app/public
    restart: always
    ports:
      - '2323:2323'
    environment:
      - NODE_ENV=production
