services:
  blog-next:
    container_name: blog-next
    image: crpi-xc0zmevg27znkp2g.cn-chengdu.personal.cr.aliyuncs.com/suqingyao/blog-next:latest
    restart: always
    ports:
      - '2323:2323'
    environment:
      - NODE_ENV=production
      - SPARK_API_PASSWORD=${SPARK_API_PASSWORD}
      - OSS_ACCESS_KEY_ID=${OSS_ACCESS_KEY_ID}
      - OSS_ACCESS_KEY_SECRET=${OSS_ACCESS_KEY_SECRET}
      - NEXT_PUBLIC_OSS_REGION=${NEXT_PUBLIC_OSS_REGION}
      - NEXT_PUBLIC_OSS_BUCKET=${NEXT_PUBLIC_OSS_BUCKET}
      - NEXT_PUBLIC_OUR_DOMAIN=${NEXT_PUBLIC_OUR_DOMAIN}
      - NEXT_PUBLIC_SITE_LINK_PREVIEW_ENABLED=${NEXT_PUBLIC_SITE_LINK_PREVIEW_ENABLED}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
